### ISSUE TITLE
Is it possible render template without $data param?

### ISSUE THREAD

**Issue by shinriyo** [brakmic/nickel-demo#1]
I always watch sample `render` method with `$data`
but, I can't find wihtoout `$data` param.

```
            return res.render("src/templates/main.tpl");
```

is best.
but, `render` method's 2nd param is not optional

So, I always set dummy data....

```
            let mut data = HashMap::<&str, &str>::new();
            data.insert("dummy", "dymmy");
            return res.render("src/templates/main.tpl", &data);
```

**Comment by brakmic** [comment]
Hi,

This question should better be posted at nickel.rs GitHub pages. I've used nickel.rs only for testing purposes and have no deeper knowledge on that subject. Sorry.

Kind regards

**Comment by shinriyo** [comment]
Hi
Thank you for replying.
I will do so.
